spring:
  application:
    name: api-customer
  security:
    oauth2:
      client:
        registration:
            datawarehousereader:
                authorization-grant-type: ${config.spring.security.oauth2.client.registration.datawarehousereader.authorization-grant-type}
                client-id: ${config.spring.security.oauth2.client.registration.datawarehousereader.client-id}
                client-secret: ${config.spring.security.oauth2.client.registration.datawarehousereader.client-secret}
                provider: ${config.spring.security.oauth2.client.registration.datawarehousereader.provider}
logging:
  level:
    root: ${config.logging.level.root}
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
integration:
  datawarehousereader:
    url: ${config.integration.datawarehousereader.url}
    connect-timeout: ${config.integration.datawarehousereader.connect-timeout}
    read-timeout: ${config.integration.datawarehousereader.read-timeout}
resilience4j:
  circuitbreaker:
    instances:
      datawarehousereader:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
