config:
  integration:
    datawarehousereader:
      url: http://datawarehousereader.url
  spring:
    security:
      oauth2:
        client:
          provider:
            datawarehousereader:
              token-uri: http://token.url
          registration:
            datawarehousereader:
              client-id: the-client-id
              client-secret: the-client-secret
logging:
  level:
    root: DEBUG