spring:
  application:
    name: api-service-installation
  security:
    oauth2:
      client:
        registration:
          datawarehousereader:
            authorization-grant-type: client_credentials
            provider: datawarehousereader
            client-id: ${config.integration.datawarehousereader.client-id}
            client-secret: ${config.integration.datawarehousereader.client-secret}
        provider:
          datawarehousereader:
            token-uri: ${config.integration.datawarehousereader.token-url}
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
integration:
  datawarehousereader:
    url: ${config.integration.datawarehousereader.base-url}
    connect-timeout: ${config.integration.datawarehousereader.connect-timeout}
    read-timeout: ${config.integration.datawarehousereader.read-timeout}
resilience4j:
  circuitbreaker:
    instances:
      datawarehousereader:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
