config:
  integration:
    datawarehousereader:
      base-url: http://datawarehousereader.url
      connect-timeout: 20
      read-timeout: 115
  spring:
    security:
      oauth2:
        client:
          provider:
            datawarehousereader:
              token-url: http://localhost:${wiremock.server.port}/token
          registration:
            datawarehousereader:
              client-id: the-client-id
              client-secret: the-client-secret
logging:
  level:
    root: INFO